### PR TITLE
Prepopulate the Authorization Code in the SSO URL

### PR DESCRIPTION
**Pull request by shaundewberry**
Allows to skip the copy-paste step and prepopulates the authorization code in the browser login.

### CODE REVIEW

**Comment by shaundewberry** [comment]
Will rather pull from next branch and recreate PR so as not to include other contributions.

**Comment by shaundewberry** [comment]
Clearly, I'm an amateur at this... Sorry.

**Comment by benkehoe** [comment]
If I understand correctly, the change you're looking to make is to `browser.py`. I want to keep that message mostly in sync with the AWS CLI's `aws sso login` command, which is implemented [here](https://github.com/aws/aws-cli/blob/d794e9815a1d91f9268f7c28d6a345e9faeb5bbe/awscli/customizations/sso/utils.py#L109). I notice that they have added the `verificationUriComplete` URL to the message (well, only when you're using `--no-browser`), which is what you're looking for (there's no guarantee that the format for putting the code in the plain URL remains stable, that's why there's [a separate parameter returned by the API](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/API_StartDeviceAuthorization.html#singlesignon-StartDeviceAuthorization-response-verificationUriComplete) for it).

So, with that in mind, here's how I'd like to do it:
* Add two parameters to the call to `self._message.format` on line 70 (the idea is there's a friendly name and one matching the API):
  * `urlWithCode=verificationUriComplete`
  * `verificationUriComplete=verificationUriComplete`
* Update the two messages `DEFAULT_BROWSER_MESSAGE` and `DEFAULT_NO_BROWSER_MESSAGE` to append the lines from the CLI starting "Alternatively..." [seen here](https://github.com/aws/aws-cli/blob/d794e9815a1d91f9268f7c28d6a345e9faeb5bbe/awscli/customizations/sso/utils.py#L115), but use `urlWithCode` rather than `verificationUriComplete`.

Does that make sense? I would also ask that you update the PR to be just a single clean commit to be added to the `next` branch.

**Comment by shaundewberry** [comment]
Thank you for the excellent guidance. I am implementing as per your suggestion and testing now.

**Pull request closed without merging**
