### PR TITLE
deps: update to use pyyaml 6

### LINKED ISSUE #104: package doesn't install
I'm having problems installing the package with `pipx`.
I started troubleshooting, since the issue is building `pyyaml`.
```
pip seemed to fail to build package:
    pyyaml<6.0.0,>=5.3.1

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: cython_sources
Error installing aws-sso-util.
```
As stated in the issue linked below, this seems to be a problem since some Cython release around 3.0.0
#https://github.com/yaml/pyyaml/issues/601

If anyone has a hotfix for this, please let me know, I'm pressed for time...

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #104

relates to https://github.com/yaml/pyyaml/issues/601

### CODE REVIEW

**Comment by benkehoe** [comment]
This has to be `>=6.0.1` I think, per https://github.com/yaml/pyyaml/pull/702 . I've shipped that and a couple changes that were waiting as v4.32.

**Comment by chenrui333** [comment]
> This has to be `>=6.0.1` I think, per [yaml/pyyaml#702](https://github.com/yaml/pyyaml/pull/702) . I've shipped that and a couple changes that were waiting as v4.32.

hmm, how is that different from `^6.0`?

**Comment by benkehoe** [comment]
`^6.0` is equivalent to `>=6.0, <7.0`, which allows `6.0.0`, which doesn't force the Cython version to be less than 3 (the change introduced in `6.0.1`).

**Comment by chenrui333** [comment]
that is fair.

**Pull request closed without merging**
