### PR TITLE
Don't return Suspended accounts when listing by OU

### LINKED ISSUE #80: Recursive assignments try to deploy to accounts in the `SUSPENDED` state
When using the Cloudformation macro and pointing an Assignment recursively at the root id `r-xxx` the output template will attempt to create assignments for accounts in a Suspended state - this eventually times out and fails, and of course Cloudformation then rolls everything back

```
Resource handler returned message: "Error occurred during operation 'Request REDACTED failed due to: 
AWS SSO is unable to complete your request at this time. 
Obtaining permissions to manage your AWS account 'REDACTED' is taking longer than usual.
```

### PR DESCRIPTION
**Pull request by Anton0**
The boto call [list_accounts_for_parent](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_accounts_for_parent) includes accounts in with statuses `'ACTIVE'|'SUSPENDED'|'PENDING_CLOSURE'`

However assignments cannot be deployed to accounts in the `SUSPENDED` state, trying to results in Cloudformation stalling and eventually returning an error when using the macro:

```
Resource handler returned message: "Error occurred during operation 'Request REDACTED failed due to: 
AWS SSO is unable to complete your request at this time. 
Obtaining permissions to manage your AWS account 'REDACTED' is taking longer than usual.
```

Worth noting the same behavior occurs in the SSO web ui - you are permitted to begin creating the assignment, then it hangs on processing until eventually timing out

I'm not sure if there's a use case for deploying assignments to an account in `PENDING_CLOSURE` nor do I have an account to test that with, but it's easy enough to return those as well if you think it's worth allowing.

I'm only using the macro, but I have tested against our accounts and this works as expected.

Resolves #80 hopefully :crossed_fingers:

### CODE REVIEW

**Comment by benkehoe** [comment]
I will take a look at this next week. It makes sense but I want to see if it makes sense to make the filtering configurable.

**Comment by stedrow** [comment]
+1 to this PR, I hit this issue recently. Is this something that can be added in, or is there another solution to this issue already implemented?

**Comment by benkehoe** [comment]
Sorry for the delay; this looks mostly good. A couple of changes I'd like:
* Add a parameter `exclude_inactive_accts=False` to the `lookup_accounts_for_ou` function, and add it to the status check `if` statement.
* Move the check to after the caching line.
* Add `exclude_inactive_accts=True` to the calls on line 233 of `cli/src/aws_sso_util/cfn.py` and line 105 of `src/aws_sso_util/cfn_lib/macro.py`.
* Add yourself to [CONTRIBUTORS.md](https://github.com/benkehoe/aws-sso-util/blob/master/CONTRIBUTORS.md) (if you want).

**Comment by Anton0** [comment]
Thank you for the detailed review! I believe this addresses all the changes, and I've tested this again in our environment (though only an update operation).

**Comment by benkehoe** [comment]
This looks good, one minor style change: you've got `if account["Status"] != "ACTIVE" and exclude_inactive_accts is True`. As a rule, I'd put the exclusion check first, because often the thing you're disabling is expensive or may not work correctly (e.g., imagine if accounts didn't always have status or something). It doesn't matter here but I think it makes sense to always do it that way. And then I'd only use an `is True` check if I'm expecting that the value can be something other than `True` or `False` and I want specifically to check for `True` instead of truthy. [Here's an example](https://github.com/benkehoe/aws-assume-role-lib/blob/84a50b1d7a821472a882225ed7d33ad2b40607ff/aws_assume_role_lib/aws_assume_role_lib.py#L225) I have where the value can be boolean or string, so I check specifically for `is True`. Can you change it to `if exclude_inactive_accts and account["Status"] != "ACTIVE"`?

**Comment by Anton0** [comment]
That all makes perfect sense to me, thank you! (and updated)

**Pull request merged**
